# Generated by Django 4.2 on 2023-04-15 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Issiue",
            new_name="Issue",
        ),
    ]
