# Generated by Django 4.2 on 2023-04-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="crud.project",
            ),
            preserve_default=False,
        ),
    ]
